
###
POST https://localhost/api/auth/signup
Authorization: Basic token
Content-Type: application/json

{
    "username": "+62812345678912"
}

###
POST https://localhost/api/auth/signin
Authorization: Basic token
Content-Type: application/json

{
    "username": "+6281935155404"
}

### 
POST https://localhost/api/auth/challenge
Authorization: Basic token
Content-Type: application/json

{
    "username": "+6281935155404",
    "password": "995532"
}

###
GET https://localhost/api/auth/refresh
Authorization: Bearer {{refresh_token}}

###
GET https://localhost/api/auth/signout
Authorization: Bearer {{access_token}}
