
### Registration
POST http://localhost/api/auth/signup
Authorization: Basic token
Content-Type: application/json

{
    "username": "+6212345678916"
}

### Login
POST http://localhost/api/auth/signin
Authorization: Basic token
Content-Type: application/json

{
    "username": "{{auth_username}}"
}

### Verify / Create token
POST http://localhost/api/auth/challenge
Authorization: Basic token
Content-Type: application/json

{
    "username": "{{auth_username}}",
    "password": "650920"
}

### Refresh / Renew token
GET http://localhost/api/auth/refresh
Authorization: Bearer {{refresh_token}}

### Logout / Revoke token
GET http://localhost/api/auth/signout
Authorization: Bearer {{access_token}}
