
### Registration
POST https://localhost/api/auth/signup
Authorization: Basic token
Content-Type: application/json

{
    "username": "+6212345678916"
}

### Login
POST https://localhost/api/auth/signin
Authorization: Basic token
Content-Type: application/json

{
    "username": "{{auth_username}}"
}

### Verify / Create token
POST https://localhost/api/auth/challenge
Authorization: Basic token
Content-Type: application/json

{
    "username": "{{auth_username}}",
    "password": "524088"
}

### Refresh / Renew token
GET https://localhost/api/auth/refresh
Authorization: Bearer {{refresh_token}}

### Logout / Revoke token
GET https://localhost/api/auth/signout
Authorization: Bearer {{access_token}}
