### Tambah bank
POST {{base}}/api/bank
Content-Type: application/json

{
    "corp_id": "{{bnidirect_corp_id}}",
    "user_id": "{{bnidirect_user_id}}",
    "password": "{{bnidirect_password}}",
    "norek": "{{bnidirect_norek}}",
    "service": "bnidirect",
    "auto_start": 0,
    "interval": 60000
}

### Bank
GET {{base}}/api/bank

### Bank account
GET {{base}}/api/bank?norek={{bnidirect_norek}}

### Setting...
PATCH {{base}}/api/bank
Content-Type: application/json

{
    "corp_id": "{{bnidirect_corp_id}}",
    "user_id": "{{bnidirect_user_id}}",
    "password": "{{bnidirect_password}}",
    "norek": "{{bnidirect_norek}}",
    "service": "bnidirect",
    "auto_start": 1,
    "interval": 60000
}

### Remove
DELETE {{base}}/api/bank?norek={{bnidirect_norek}}

### Login
GET {{base}}/api/bank/login?norek={{bnidirect_norek}}

### Logout
GET {{base}}/api/bank/logout?norek={{bnidirect_norek}}

### History
GET {{base}}/api/bank/history?norek={{bnidirect_norek}}&fromDate=2023-05-01&toDate=2023-05-28
