### Tambah bank
POST {{base}}/api/bank
Content-Type: application/json

{
    "corp_id": "{{ibank_corp_id}}",
    "user_id": "{{ibank_user_id}}",
    "password": "{{ibank_password}}",
    "norek": "{{ibank_norek}}",
    "service": "ibank",
    "auto_start": 0,
    "interval": 60000
}

### Bank
GET {{base}}/api/bank

### Bank account
GET {{base}}/api/bank?norek={{ibank_norek}}

### Setting...
PATCH {{base}}/api/bank
Content-Type: application/json

{
    "corp_id": "{{ibank_corp_id}}",
    "user_id": "{{ibank_user_id}}",
    "password": "{{ibank_password}}",
    "norek": "{{ibank_norek}}",
    "service": "ibank",
    "auto_start": 1,
    "interval": 60000
}

### Remove
DELETE {{base}}/api/bank?norek={{ibank_norek}}

### Login
GET {{base}}/api/bank/login?norek={{ibank_norek}}

### Logout
GET {{base}}/api/bank/logout?norek={{ibank_norek}}

### History
GET {{base}}/api/bank/history?norek={{ibank_norek}}&fromDate=2023-05-01&toDate=2023-05-28
