### Tambah bank
POST {{base}}/api/bank
Content-Type: application/json

{
    "corp_id": "{{newbiz_corp_id}}",
    "user_id": "{{newbiz_user_id}}",
    "password": "{{newbiz_password}}",
    "norek": "{{newbiz_norek}}",
    "service": "newbiz",
    "auto_start": 0,
    "interval": 60000
}

### Bank
GET {{base}}/api/bank

### Bank account
GET {{base}}/api/bank?norek={{newbiz_norek}}

### Setting...
PATCH {{base}}/api/bank
Content-Type: application/json

{
    "corp_id": "{{newbiz_corp_id}}",
    "user_id": "{{newbiz_user_id}}",
    "password": "{{newbiz_password}}",
    "norek": "{{newbiz_norek}}",
    "service": "newbiz",
    "auto_start": 1,
    "interval": 60000
}

### Remove
DELETE {{base}}/api/bank?norek={{newbiz_norek}}

### Login
GET {{base}}/api/bank/login?norek={{newbiz_norek}}

### Logout
GET {{base}}/api/bank/logout?norek={{newbiz_norek}}

### History
GET {{base}}/api/bank/history?norek={{newbiz_norek}}
