### Tambah bank
POST http://localhost/api/bank
Content-Type: application/json

{
    "corp_id": "{{newbiz_corp_id}}",
    "user_id": "{{newbiz_user_id}}",
    "password": "{{newbiz_password}}",
    "norek": "{{newbiz_norek}}",
    "service": "newbiz",
    "auto_start": 0,
    "interval": 60000
}

### Bank
GET http://localhost/api/bank

### Bank account
GET http://localhost/api/bank?norek={{newbiz_norek}}

### Setting...
PATCH http://localhost/api/bank
Content-Type: application/json

{
    "corp_id": "{{newbiz_corp_id}}",
    "user_id": "{{newbiz_user_id}}",
    "password": "{{newbiz_password}}",
    "norek": "{{newbiz_norek}}",
    "service": "newbiz",
    "auto_start": 1,
    "interval": 60000
}

### Remove
DELETE http://localhost/api/bank?norek={{newbiz_norek}}

### Login
GET http://localhost/api/bank/login?norek={{newbiz_norek}}

### Logout
GET http://localhost/api/bank/logout?norek={{newbiz_norek}}

### History
GET http://localhost/api/bank/history?norek={{newbiz_norek}}
