### config
GET http://localhost/api/sidompul/config

### config
POST http://localhost/api/sidompul/config
Content-Type: application/json

{
    "postPackage": {},
    "getTransactionhistory": {},
    "postW2p": {},
    "getDompulBalance": {},
    "getPulsaBalance": {},
    "getProductList": {},
    "postPackagePulsa": {},
    "getAwgStock": {},
    "getAwgTransactioninfo": {},
    "postAwgTransactionInfoDetail": {
        "API": "",
        "API-ID": "",
        "CLIENT-ID": ""
    },
    "postAwgTembak": {},
    "getXwgStock": {},
    "getXwgTransactioninfo": {},
    "postXwgTransactionInfoDetail": {
        "API": "",
        "API-ID": "",
        "CLIENT-ID": ""
    },
    "postXwgTembak": {
        "API": "",
        "API-ID": "",
        "CLIENT-ID": ""
    },
    "getTransactionHistorydetail": {}
}

### Authorization
GET http://localhost/api/sidompul/token?grant_type=&client_id=&client_secret=

### Get Token
GET http://localhost/api/sidompul/postEncrypt?data=

### Purchase Package
GET http://localhost/api/sidompul/postPackage?msisdn=&pin=&productCode=

### Transaction History
GET http://localhost/api/sidompul/getTransactionhistory?

### Reload Pulsa (W2P)
GET http://localhost/api/sidompul/postW2p?msisdn=&pin=&denom=

### Get Dompul Balance
GET http://localhost/api/sidompul/getDompulBalance?

### Get Pulsa Balance
GET http://localhost/api/sidompul/getPulsaBalance?

### Get List Product Code
GET http://localhost/api/sidompul/getProductList?

### Purchase Package Deduct Pulsa
GET http://localhost/api/sidompul/postPackagePulsa?msisdn=&pin=&productCode=

### AWG Get Stock
GET http://localhost/api/sidompul/getAwgStock?

### AWG Get Info Transaction
GET http://localhost/api/sidompul/getAwgTransactioninfo?

### AWG Get Info Transaction Detail
GET http://localhost/api/sidompul/postAwgTransactionInfoDetail?command=&masterTrxId=

### AWG Inject Stock
GET http://localhost/api/sidompul/postAwgTembak?target=&pin=&vId=&command=&allowType=

### XWG Get Stock
GET http://localhost/api/sidompul/getXwgStock?

### XWG Get Info Transaction
GET http://localhost/api/sidompul/getXwgTransactioninfo?

### XWG Get Info Transaction Detail
GET http://localhost/api/sidompul/postXwgTransactionInfoDetail?command=&masterTrxId=

### XWG Inject Stock
GET http://localhost/api/sidompul/postXwgTembak?allowType=&command=&pin=&target=&vId=

### Transaction History Detail
GET http://localhost/api/sidompul/getTransactionHistorydetail

