### config
GET {{base}}/api/sidompul/config

### config
POST {{base}}/api/sidompul/config
Content-Type: application/json

{
    "postEncrypt": {
        "API": "",
        "API-ID": "",
        "API-KEY": ""
    },
    "postPackage": {
        "API": "",
        "API-ID": "",
        "API-KEY": ""
    },
    "getTransactionhistory": {
        "API": "",
        "API-ID": "",
        "API-KEY": ""
    },
    "postW2p": {
        "API": "",
        "API-ID": "",
        "API-KEY": ""
    },
    "getDompulBalance": {
        "API": "",
        "API-ID": "",
        "API-KEY": ""
    },
    "getPulsaBalance": {
        "API": "",
        "API-ID": "",
        "API-KEY": ""
    },
    "getProductList": {
        "API": "",
        "API-ID": "",
        "API-KEY": ""
    },
    "postPackagePulsa": {
        "API": "",
        "API-ID": "",
        "API-KEY": ""
    },
    "getAwgStock": {
        "API": "",
        "API-ID": "",
        "API-KEY": ""
    },
    "getAwgTransactioninfo": {
        "API": "",
        "API-ID": "",
        "API-KEY": ""
    },
    "postAwgTransactionInfoDetail": {
        "API": "",
        "API-ID": "",
        "API-KEY": ""
    },
    "postAwgTembak": {
        "API": "",
        "API-ID": "",
        "API-KEY": ""
    },
    "getXwgStock": {
        "API": "",
        "API-ID": "",
        "API-KEY": ""
    },
    "getXwgTransactioninfo": {
        "API": "",
        "API-ID": "",
        "API-KEY": ""
    },
    "postXwgTransactionInfoDetail": {
        "API": "",
        "API-ID": "",
        "API-KEY": ""
    },
    "postXwgTembak": {
        "API": "",
        "API-ID": "",
        "API-KEY": ""
    },
    "getTransactionHistorydetail": {
        "API": "",
        "API-ID": "",
        "API-KEY": ""
    }
}

### Get Token
GET {{base}}/api/sidompul/token?grant_type=client_credentials&client_id={{sidompul_client_id}}&client_secret={{sidompul_client_secret}}

### Encrypt
GET {{base}}/api/sidompul/postEncrypt?data=123456

### Purchase Package
GET {{base}}/api/sidompul/postPackage?msisdn=&pin=&productCode=

### Transaction History
GET {{base}}/api/sidompul/getTransactionhistory?startdate=&enddate=

### Reload Pulsa (W2P)
GET {{base}}/api/sidompul/postW2p?msisdn=&pin=&denom=

### Get Dompul Balance
GET {{base}}/api/sidompul/getDompulBalance?

### Get Pulsa Balance
GET {{base}}/api/sidompul/getPulsaBalance?

### Get List Product Code
GET {{base}}/api/sidompul/getProductList?

### Purchase Package Deduct Pulsa
GET {{base}}/api/sidompul/postPackagePulsa?msisdn=&pin=&productCode=

### AWG Get Stock
GET {{base}}/api/sidompul/getAwgStock?

### AWG Get Info Transaction
GET {{base}}/api/sidompul/getAwgTransactioninfo?beginDate=&endDate=&servicetype=

### AWG Get Info Transaction Detail
GET {{base}}/api/sidompul/postAwgTransactionInfoDetail?command=&masterTrxId=

### AWG Inject Stock
GET {{base}}/api/sidompul/postAwgTembak?target=&pin=&vId=&command=&allowType=

### XWG Get Stock
GET {{base}}/api/sidompul/getXwgStock?roType=MINI-GROSIR

### XWG Get Info Transaction
GET {{base}}/api/sidompul/getXwgTransactioninfo?beginDate=&endDate=&servicetype=

### XWG Get Info Transaction Detail
GET {{base}}/api/sidompul/postXwgTransactionInfoDetail?command=&masterTrxId=

### XWG Inject Stock
GET {{base}}/api/sidompul/postXwgTembak?allowType=&command=&pin=&target=&vId=

### Transaction History Detail
GET {{base}}/api/sidompul/getTransactionHistorydetail?transactionId=&msisdnB=&orderStatus=

