### Tambah center
POST {{base}}/api/messenger
Content-Type: application/json

{
    "username":"{{telegram_username}}",
    "password":"{{telegram_password}}",
    "service":"telegram",
    "startup_login":0,
    "center":1
}

### Center
GET {{base}}/api/messenger

### Center account
GET {{base}}/api/messenger?username={{telegram_username}}

### Setting...
PATCH {{base}}/api/messenger
Content-Type: application/json

{
    "username":"{{telegram_username}}",
    "password":"{{telegram_password}}",
    "service":"telegram",
    "startup_login":1,
    "center":1
}

### Remove
DELETE {{base}}/api/messenger?username={{telegram_username}}

### Login
GET {{base}}/api/messenger/start?username={{telegram_username}}

### Logout
GET {{base}}/api/messenger/stop?username={{telegram_username}}

### Kirim
POST {{base}}/api/messenger/send
Content-Type: application/json

{
    "username":"{{telegram_username}}",
    "service":"telegram",
    "penerima":"1344008938",
    "pesan":"This message from server"
}

### Kirim
GET {{base}}/api/messenger/send?username={{telegram_username}}&service=telegram&penerima=1344008938&pesan=This message from server
