### Tambah center
POST http://localhost/api/messenger
Content-Type: application/json

{
    "username":"{{telegram_username}}",
    "password":"{{telegram_password}}",
    "service":"telegram",
    "startup_login":0,
    "sender_speed":0,
    "service_center":1
}

### Center
GET http://localhost/api/messenger

### Center account
GET http://localhost/api/messenger?username={{telegram_username}}

### Setting...
PATCH http://localhost/api/messenger
Content-Type: application/json

{
    "username":"{{telegram_username}}",
    "password":"{{telegram_password}}",
    "service":"telegram",
    "startup_login":1,
    "sender_speed":0,
    "service_center":1
}

### Remove
DELETE http://localhost/api/messenger?username={{telegram_username}}

### Login
GET http://localhost/api/messenger/start?username={{telegram_username}}

### Logout
GET http://localhost/api/messenger/stop?username={{telegram_username}}

### Kirim
POST http://localhost/api/messenger/send
Content-Type: application/json

{
    "username":"{{telegram_username}}",
    "service":"telegram",
    "penerima":"1344008938",
    "pesan":"This message from server"
}

### Kirim
GET http://localhost/api/messenger/send?username={{telegram_username}}&service=telegram&penerima=1344008938&pesan=This message from server
