### Tambah center
POST http://localhost/api/messenger
Content-Type: application/json

{
    "username":"5924975288",
    "password":"5924975288:AAE6uNUymvOBhpHyX1mY6GctqmcZR1YxOWA",
    "service":"telegram",
    "startup_login":1,
    "center":1
}

### Center
GET http://localhost/api/messenger

### Center account
GET http://localhost/api/messenger?username=5924975288

### Setting...
PATCH http://localhost/api/messenger
Content-Type: application/json

{
    "username":"5924975288",
    "password":"5924975288:AAE6uNUymvOBhpHyX1mY6GctqmcZR1YxOWA",
    "service":"telegram",
    "startup_login":0
}

### Remove
DELETE http://localhost/api/messenger?username=5924975288

### Login
GET http://localhost/api/messenger/start?username=5924975288

### Logout
GET http://localhost/api/messenger/stop?username=5924975288

### Kirim
POST http://localhost/api/messenger/send
Content-Type: application/json

{
    "username":"5924975288",
    "service":"telegram",
    "penerima":"1344008938",
    "pesan":"This message from server"
}

### Kirim
GET http://localhost/api/messenger/send?username=5924975288&service=telegram&penerima=1344008938&pesan=This message from server
