### Tambah center
POST http://localhost/api/messenger
Content-Type: application/json

{
    "username":"6281938064470",
    "password":"",
    "service":"whatsapp",
    "startup_login":1,
    "center":1
}

### Center
GET http://localhost/api/messenger

### Center account
GET http://localhost/api/messenger?username=6281938064470

### Setting...
PATCH http://localhost/api/messenger
Content-Type: application/json

{
    "username":"6281938064470",
    "password":"",
    "service":"whatsapp",
    "startup_login":0
}

### Remove
DELETE http://localhost/api/messenger?username=6281938064470

### Login
GET http://localhost/api/messenger/start?username=6281938064470

### Logout
GET http://localhost/api/messenger/stop?username=6281938064470

### Kirim
POST http://localhost/api/messenger/send
Content-Type: application/json

{
    "username":"6281938064470",
    "service":"whatsapp",
    "penerima":"6281935155404",
    "pesan":"This message from server"
}

### Kirim
GET http://localhost/api/messenger/send?username=6281938064470&service=whatsapp&penerima=6281935155404&pesan=This message from server
