### Tambah center
POST {{base}}/api/messenger
Content-Type: application/json

{
    "username":"{{whatsapp_username}}",
    "password":"",
    "service":"whatsapp",
    "startup_login":0,
    "sender_speed":0,
    "center":1
}

### Center
GET {{base}}/api/messenger

### Center account
GET {{base}}/api/messenger?username={{whatsapp_username}}

### Setting...
PATCH {{base}}/api/messenger
Content-Type: application/json

{
    "username":"{{whatsapp_username}}",
    "password":"",
    "service":"whatsapp",
    "startup_login":1,
    "sender_speed":0,
    "center":1
}

### Remove
DELETE {{base}}/api/messenger?username={{whatsapp_username}}

### Login
GET {{base}}/api/messenger/start?username={{whatsapp_username}}

### Logout
GET {{base}}/api/messenger/stop?username={{whatsapp_username}}

### Kirim
POST {{base}}/api/messenger/send
Content-Type: application/json

{
    "username":"{{whatsapp_username}}",
    "service":"whatsapp",
    "penerima":"6281935155404",
    "pesan":"test"
}

### Kirim
GET {{base}}/api/messenger/send?username={{whatsapp_username}}&service=whatsapp&penerima=6281935155404&pesan=This message from server
